.changeset/early-hounds-draw.md
.github/workflows/new-pr-to-main.yaml
.github/workflows/release.yml
docker-compose.yml
package.json
scripts/check_changeset.sh

- ¿Qué cambio?
- Las capturas de pantalla antes/después también pueden ser útiles.
- No olvides a **changeset**! `pnpm exec changeset`

refactor: docker compose

---

.changeset/silver-items-wave.md
packages/legend-transac/README.md
packages/schema-validator/.eslintrc.json
packages/schema-validator/README.md
packages/schema-validator/package.json
packages/schema-validator/src/index.ts
packages/schema-validator/src/schemaType.ts
packages/schema-validator/tsconfig.json
pnpm-lock.yaml
turbo.json

Nueva librearía para parsear un **json string** a un objeto de comandos de microservicios.
Se realiza los jsdoc correspondientes

feat: new lib schema validator

---

.github/workflows/check-dependencies.yml
payload.json

- ¿Qué cambio?
Se refactoriza action que actualiza dependencias con soporte para multiples `package.json` en el proyecto.
No necesita `docs`

feat: action support deep package.json

---

.changeset/clever-baboons-bow.md
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/index.ts
packages/legend-transac/src/@types/saga/commands/pagosv2.ts
packages/legend-transac/src/@types/saga/commands/social.ts
packages/legend-transac/src/@types/saga/microservices.ts

- ¿Que cambió?
- No olvides ejecutar [**changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo) `pnpm exec changeset`
- Si sigues enviando `commits` mejor [convierte la PR en un `draft`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)
ó creala como [`draft` desde el principio](https://github.blog/2019-02-14-introducing-draft-pull-requests/#tag-your-work-in-progress) y cuando esté lista la conviertes en una PR [Ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-t …

feat: social and pagosv2

---

.changeset/sharp-glasses-study.md
.ncurc.json
package.json
packages/eslint-config-custom/index.js
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/pagosv2.ts
packages/legend-transac/src/@types/saga/commands/social.ts
packages/legend-transac/src/@types/saga/microservices.ts
pnpm-lock.yaml

- ¿Que cambió?
- No olvides ejecutar [**changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo) `pnpm exec changeset`
- Si sigues enviando `commits` mejor [convierte la PR en un `draft`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)
ó creala como [`draft` desde el principio](https://github.blog/2019-02-14-introducing-draft-pull-requests/#tag-your-work-in-progress) y cuando esté lista la conviertes en una PR [Ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-t …

feat: update dependencies

---

.changeset/smart-elephants-beg.md
packages/legend-transac/src/@types/saga/commands/integrations.ts
packages/legend-transac/src/@types/saga/commands/pagosv2.ts

Comandos para poner y cancelar venta de nfts
Se escribe la doc correctamente

feat: cancel sale put nft on sale

---

.changeset/kind-dogs-provide.md
packages/legend-transac/src/Consumer/channels/Consume.ts
packages/legend-transac/src/Consumer/channels/Microservice.ts
packages/legend-transac/src/Consumer/channels/Saga.ts
packages/legend-transac/src/utils/fibonacci.ts
packages/legend-transac/src/utils/index.ts

Se agrega nacking con nackeo infinito y delay siguiendo la serie de fibonacci.
Se documenta todos los métodos involucrados, excepto la serie de fibo, se explica por si sola.

Infinite Nacking with fibonnaci delay

---

.changeset/tender-avocados-wave.md
apps/image/src/handler.ts
apps/image/src/server.ts
apps/mint/src/handler.ts
apps/mint/src/server.ts
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/image.ts
packages/legend-transac/src/@types/saga/commands/mint.ts
packages/legend-transac/src/@types/saga/microservices.ts
pnpm-lock.yaml

Se cambia los nombres en los comandos, micros de test
Solo se cambio los nombres en los comandos, micros de test, los docs quedaron iguales

feat: test names in saga changed

---

.changeset/itchy-flies-build.md
packages/legend-transac/src/Consumer/channels/Consume.ts
packages/legend-transac/src/Consumer/channels/Microservice.ts

Se añade "\_\_metadata" keys en el payload, este payload siempre será incluido en todo el saga incluso si no se pasa el payload al siguiente paso explícitamente.
Se refactoriza algo existente

feat: mandatory metada payload if exists

---

.changeset/rare-camels-explain.md
packages/legend-transac/src/@types/saga/commands/analytics.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/eventsadmin.ts
packages/legend-transac/src/@types/saga/commands/index.ts
packages/legend-transac/src/@types/saga/microservices.ts

Se agrega los microservicos de **events-admin** y **legend-analytics** junto con los comandos para comprar productos
Se documenta los nuevos microservicios y comandos

Adding analytics

---

.changeset/soft-peaches-ring.md
packages/legend-transac/src/Consumer/channels/CommenceSaga.ts
packages/legend-transac/src/Consumer/channels/Consume.ts
packages/legend-transac/src/Consumer/channels/Microservice.ts
packages/legend-transac/src/Consumer/channels/Saga.ts

feat: major release

---

.changeset/soft-pigs-double.md
packages/legend-transac/src/@types/saga/consumer.ts
packages/legend-transac/src/@types/saga/saga.ts
packages/legend-transac/src/@types/saga/step/handler.ts
packages/legend-transac/src/Broker/SendToQueue.ts
packages/legend-transac/src/Connections/start.ts
packages/legend-transac/src/Consumer/callbacks/commenceSaga.ts
packages/legend-transac/src/Consumer/channels/CommenceSaga.ts
packages/legend-transac/src/Consumer/consume.ts

Payload obtiene nuevos tipo 
Se documenta todo

feat: T in payload saga extends Record<string, any>

---

.changeset/brave-clocks-arrive.md
packages/legend-transac/src/Connections/start.ts

Se agreaga tipos al `startSaga`
Refactor de tipos

feat: types in startSaga

---

.changeset/thin-dryers-cover.md
packages/legend-transac/src/@types/saga/consumer.ts
packages/legend-transac/src/@types/saga/saga.ts
packages/legend-transac/src/@types/saga/step/handler.ts
packages/legend-transac/src/Connections/start.ts
packages/legend-transac/src/Consumer/callbacks/commenceSaga.ts
packages/legend-transac/src/Consumer/channels/CommenceSaga.ts

Payload del saga commence tiene tipo `any`
Solo es un refactor de tipos

feat: types any for payload in saga commence

---

.changeset/chatty-buckets-cry.md
packages/legend-transac/src/@types/saga/commands/eventsadmin.ts

Nuevo comando en el micro de `events-admin`
Se documenta el comando

feat: products send email cmd

---

.changeset/smart-glasses-train.md
packages/legend-transac/src/@types/saga/saga.ts

Se agrega un nuevo saga `persist_redsys`
Se documenta todo

feat: new saga persist_redsys

---

.changeset/fifty-rice-decide.md
packages/legend-transac/src/Connections/health.ts
packages/legend-transac/src/Connections/index.ts

Health check para colas con nombre
Se documenta todo

faet: isqueuehealthy

---

.changeset/purple-garlics-yawn.md
packages/legend-transac/src/Connections/rabbitConn.ts

Se agrega mejores logs de error
No necesita, solo son console.log

feat: better error logs

---

.changeset/warm-actors-teach.md
packages/legend-transac/src/@types/saga/commands/avatarClothes.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/index.ts
packages/legend-transac/src/@types/saga/commands/notifications.ts
packages/legend-transac/src/@types/saga/microservices.ts

Se agrega el micro `legend-avatar-clothes`
Se documenta el nuevo micro

feat: avatar legend clothes

---

.changeset/swift-starfishes-grow.md
packages/legend-transac/src/@types/saga/commands/eventsadmin.ts
packages/legend-transac/src/@types/saga/commands/integrations.ts
packages/legend-transac/src/@types/saga/commands/social.ts

Se agreagan los comandos necesarios para los nuevo saga `buy_image_asset` `buy_room_asset`
Se documenta todos los nuevos comandos

feat: buy iamge asset, room asset

---

.ncurc.json
package.json
packages/eslint-config-custom/package.json
pnpm-lock.yaml

Se actualiza dependencias, se bloquea la actualización de `@swc/cli`

feat: update dep

---

.changeset/clever-cars-relate.md
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/Consumer/nack.ts
pnpm-lock.yaml

-   ¿Que cambió?
-   No olvides ejecutar [**changeset**](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md#i-am-in-a-multi-package-repository-a-mono-repo) `pnpm exec changeset`
-   Si sigues enviando `commits` mejor [convierte la PR en un `draft`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)
ó creala como [`draft` desde el principio](https://github.blog/2019-02-14-introducing-draft-pull-requests/#tag-your-work-in-progress) y cuando esté lista la conviertes en una PR [Ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/chan …

feat: testing flow

---

.changeset/few-stingrays-remain.md
.changeset/three-gifts-exist.md
actions/check-changeset/package.json
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/saga/commands/auth.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/index.ts
packages/legend-transac/src/@types/saga/commands/roomCreator.ts
packages/legend-transac/src/@types/saga/commands/showcase.ts
packages/legend-transac/src/@types/saga/commands/social.ts
packages/legend-transac/src/@types/saga/microservices.ts
packages/legend-transac/src/@types/saga/saga.ts
pnpm-lock.yaml

Se agrega comandos y microservicios relacionados con la creación de nuevos usuarios de Legendaryum
Se documenta todo la refactorización involucrada

Le 1463  Commands and Microservices related to create new user flow

---

.changeset/neat-geckos-jam.md
packages/legend-transac/src/Broker/SendToQueue.ts

Se agrega el parámetro **uri** en la función **commenceSaga** con la intención de darle independencia al empezar un saga.
Se documenta el cambio en la función.

refactor: commenceSaga

---

packages/legend-transac/README.md

doc: add license

---

.changeset/gorgeous-seas-rush.md
packages/legend-transac/src/@types/microservices.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/payments.ts
packages/legend-transac/src/@types/saga/commands/room-snapshot.ts

- new saga's commands: 
- **resource_purchased:**
- **resource_purchased:deduct_coins**
- new microservice: **room-snapshot**
The purpose and usage of the events are documented

feat: new eventos for purchase resources flow

---

.github/workflows/release.yml
README.md
packages/legend-transac/README.md

**README.md** is added to the root dir.
**README.md** is added to the root dir.

docs: Readme

---

.changeset/lovely-olives-nail.md
apps/image/src/handler.ts
apps/mint/src/handler.ts
apps/saga/src/handler.ts
packages/legend-transac/src/Consumer/channels/Consume.ts

Rename **nackWithDelayAndRetries** for **nackWithDelay**, `Max Retries` is optional, otherwise the nacking is forever.
The refactor is documented in code

feat: maxRetries are optional in nacking system

---

.changeset/warm-walls-remember.md
packages/legend-transac/src/@types/microservices.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/index.ts
packages/legend-transac/src/@types/saga/commands/payments.ts
packages/legend-transac/src/@types/saga/commands/room-inventory.ts

- a new saga step has been added in payments
- new microservice "room-inventory" has been added in AvailableMicroservices
a new saga step has been added in payments and a new microservice, room-inventory, has been added in AvailableMicroservices
the documentation for the new microservice and the new saga steps are in their respective files

feat: new saga step and new microservice

---

.changeset/fuzzy-pots-boil.md
packages/legend-transac/src/@types/event/events.ts

Fix events blockChat and unblockChat to handle chats in rapid-messaging
Fix  events blockChat and unblockChat to handle chats in rapid-messaging
This events will block and unblock users in rapid messaging server.
https://legendaryum.atlassian.net/browse/LE-1852

Fix blockChat and unblockChat events

---

.changeset/tiny-insects-carry.md
packages/legend-transac/src/@types/saga/commence.ts

- removing **unityId** `prop` from **purchase_resource_flow**
- it doesn't need doc

Removing unity

---

.changeset/smart-suits-bow.md
.github/workflows/new-pr-to-main.yaml
apps/saga/src/server.ts
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/Connections/start.ts
packages/legend-transac/src/utils/getters.ts
pnpm-lock.yaml

New saga orchestrator **class**
The new class is documented

feat: transactional orchestrator

---

.changeset/fifty-countries-try.md
packages/legend-transac/src/@types/saga/commands/room-inventory.ts
packages/legend-transac/src/@types/saga/commands/room-snapshot.ts

new command 'SavePurchasedResource' in room-inventory and remove 'PurchaseResource' command in room-snapshot
new command 'SavePurchasedResource' in room-inventory and remove 'PurchaseResource' command in room-snapshot. documentation is in the respective files of each microservice's commands

feat: new command 'SavePurchasedResource' in room-inventory and remove 'PurchaseResource' command in room-snapshot

---

.changeset/dirty-zebras-enjoy.md
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/event/events.ts
pnpm-lock.yaml

- new event room_creator.created_room to create a new product virtual in showcase
new event room_creator.created_room to create a new product virtual in showcase

new event room_creator.created_room to create a new product virtual in showcase

---

.changeset/eighty-bees-lick.md

testing deploy

---

.changeset/slow-pots-pump.md
packages/legend-transac/src/constants.ts

Test branch 1

---

.changeset/honest-monkeys-rhyme.md

feat: trying fixing action

---

.changeset/soft-worms-fry.md
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/event/events.ts
pnpm-lock.yaml

new event auth.deleted_user to delete all related info
new event auth.deleted_user to delete all related info

new event auth.deleted_user to delete all related info

---

.changeset/blue-dancers-hang.md
packages/legend-transac/src/@types/event/events.ts

- update payload in room_inventory.update_vp_building_image event
-update payload in room_inventory.update_vp_building_image event
- new fields in payload: `roomType` and `userId`,  both of which are strings

feat: update payload in room_inventory.update_vp_building_image event

---

.changeset/eight-carrots-promise.md
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/saga/commands/roomCreator.ts
packages/legend-transac/src/@types/saga/commands/showcase.ts
packages/legend-transac/src/@types/saga/commence.ts
pnpm-lock.yaml

Added new saga update_island_room_template to update data from island rooms in room creators and showcase
Added new saga update_island_room_template to update data from island rooms in room creators and showcase
https://legendaryum.atlassian.net/browse/LE-2032

 Added new saga update_island_room_template

---

.changeset/fuzzy-bottles-applaud.md
packages/legend-transac/src/@types/event/events.ts

- `legend_missions.completed_mission_reward`: new event to give the user coins for completing a mission
This event will be emitted when a user completes a mission and should be given coins as a reward

feat: new event to give the user coins for completing a mission

---

.changeset/early-clocks-trade.md
package.json
packages/legend-transac/src/@types/saga/commence.ts
pnpm-lock.yaml

- The `commenceSaga` **update_island_room_template** is deleted, now is handled **sync**
Is a deletion

feat: comence saga deleted

---

.changeset/green-oranges-clean.md
packages/legend-transac/src/@types/event/events.ts

- event to set a mission in progress
- event to set a mission in progress. docs in the file

feat: event to set a mission in progress

---

.changeset/spotty-comics-love.md
.github/workflows/check-dependencies.yml
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/event/events.ts
pnpm-lock.yaml

- Event to logout a user from all micros.
- Event to logout a user from all micros. docs in the file
https://legendaryum.atlassian.net/browse/LE-2173

Event to logout a user from all micros.

---

.changeset/young-lamps-invite.md
package.json
packages/eslint-config-custom/package.json
packages/legend-transac/src/@types/saga/commands/auth.ts
packages/legend-transac/src/@types/saga/commands/social.ts
packages/legend-transac/src/@types/saga/commence.ts
pnpm-lock.yaml

- Update user picture step
- Delete commence saga update social user image
All is documented

Le 2215 update social picture

---

.changeset/mean-goats-chew.md
packages/legend-transac/src/@types/saga/commands/auth.ts
packages/legend-transac/src/@types/saga/commands/storage.ts

- auth command for update picture image deleted
All is documented

feat: auth command for update picture image deleted

---

.changeset/quick-pans-exist.md
package.json
packages/legend-transac/src/@types/event/events.ts
pnpm-lock.yaml

Coin send an event when a user subscription is updated
It is correctly documented

feat: coins update subscription event

---

.changeset/spicy-eyes-dress.md
packages/legend-transac/src/@types/event/events.ts

-  Event to delete assets in batch
- The event is documented

Event to delete assets in batch

---

.changeset/few-ducks-ring.md
packages/legend-transac/src/@types/event/events.ts

"email" is added to 'coins.send_email' event
is a new prop "email" in event

feat:  email is added to 'coins.send_email' event

---

.changeset/great-eels-collect.md
packages/legend-transac/src/@types/saga/commands/auth.ts
packages/legend-transac/src/@types/saga/commands/social.ts

Two commands step (auth, social) in the saga "create_new_user"
All is documented

feat: create new user

---

.changeset/khaki-birds-enjoy.md
packages/legend-transac/src/@types/event/events.ts

- update payload for legend_rankings.rankings_finished event
- new fields `authorEmail`, `description`, `reward` and `endsAt`
- docs in the file

feat: update payload for legend_rankings.rankings_finished event

---

.changeset/sour-ducks-deny.md
packages/legend-transac/src/@types/microservices.ts
packages/legend-transac/src/@types/saga/commands/blockchain.ts
packages/legend-transac/src/@types/saga/commands/commands.ts
packages/legend-transac/src/@types/saga/commands/index.ts

New domain: `blockchain`
Is documented the base of the `blockchain` domain

feat: new blockchain domain

---

.changeset/breezy-bananas-cross.md
packages/legend-transac/src/@types/event/events.ts

- event to update social user
- event to update social user
- docs in file

feat: event to update social user

---

.changeset/weak-ads-whisper.md
packages/legend-transac/src/@types/event/events.ts

- replace enum with string in the 'rewardType' field of the 'CompletedRanking' structure
- docs in file

feat: replace enum with string in the 'rewardType' field of the 'CompletedRanking' structure

---

.changeset/proud-singers-invite.md
packages/legend-transac/src/@types/event/events.ts

- new event 'legend_missions.new_mission_created'
- docs in file

feat: new event 'legend_missions.new_mission_created'

---

.changeset/purple-actors-love.md
packages/legend-transac/src/@types/event/events.ts

- feat: add event to notify that a user has completed a mission with crypto reward 
- docs in file

feat: add event to notify that a user has completed a mission with crypto reward

---

.changeset/cold-parrots-juggle.md
packages/legend-transac/src/@types/event/events.ts

- add events to notify by email when a user completes a mission
- add events to notify by email when a user completes a mission
- docs in file

feat: add events to notify by email when a user completes a mission
